### ISSUE TITLE
cpp00-09

### ISSUE THREAD

**Issue by habvi** [habvi/42_cpp_module#5]
- cpp00 (PR #2 )
- [x] ex00 : megaphone (PR #1 )
- [x] ex01 : phonebook (PR #3 )
- [x] ex02 : account (PR #4 )

<br>

- cpp01 (PR #9 )
- [x] ex00 : BraiiiiiiinnnzzzZ (PR #6  )
- [x] ex01 : Moar brainz! (PR #7  )
- [x] ex02 : HI THIS IS BRAIN (PR #8  )
- [x] ex03 : Unnecessary violence (PR #10 )
- [x] ex04 : Sed is for Iosers (PR #11 )
- [x] ex05 : Harl 2.0 (PR #12 )
- [x] e06 : Harl filter (PR #13 )

<br>

- cpp02 (PR #18 )
- [x] ex00 : Class in Orthodox Canonical Form, Fixed (PR #17 )
- [x] ex01 : more useful fixed-point number class (PR #19  )
- [x] ex02 : more useful operator (PR #20 )
- [x] ex03 : BSP (PR #21)

<br>

- cpp03 (PR #25 )
- [x] ex00 : ClapTrap (PR #24 )
- [x] ex01 : ScavTrap (PR #26 )
- [x] ex02 : FragTrap (PR #27)
- [x] ex03 : DiamondTrap (PR #28)

<br>

- cpp04 (PR #31 )
- [x] ex00 : Polymorphism/Animal,Dog,Cat (PR #30 )
- [x] ex01 : Brain (PR #32 )
- [x] ex02 : Abstract (PR #33 )
- [x] ex03 : Interface & recap (PR #34)

<br>

- cpp05 (PR #39  )
- [x] ex00 : Bureaucrat (#35 )
- [x] ex01 : Form (#37 )
- [x] ex02 : AForm (#40  )
- [x] ex03 : Intern (#41 )

<br>

- cpp06 (PR #46 )
- [x] ex00 : ScalarConverter (PR #43 )
- [x] ex01 : Serialization (PR #44 )
- [x] ex02 : Identify (PR #45)

<br>

- cpp07 (PR #50 )
- [x] ex00 : whatever (PR #47 )
- [x] ex01 : iter (PR #48 )
- [x] ex02 : Array (PR #49 )

<br>

- cpp08 (PR #54 )
- [x] ex00 : easyfind (PR #51 )
- [x] ex01 : Span (PR #52 )
- [x] ex02 : MutantStack (PR #53  )

<br>

- cpp09 (PR #59 )
- [x] ex00 : Bitcoin Exchange(PR #56 )
- [x] ex01 : RPN (PR #57 )
- [x] ex02 : PmergeMe (PR #58 )
